#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


# Add Docker’s official GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# Set up the stable repository
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# Can't install this with the package-installs element
# because we need to dinamically get kernel version
# and we need this to be installed in pre-install
# because packages are going to be installed in
# install.d phase
sudo apt-get install -y linux-image-extra-$(uname -r)
